language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

jobs:
  include:
    - stage: build
      script: gcc-7 random.c -o random
    - stage: test
      script:
      - ./random
      - ./random -f -d 4 -g 10
